gitea:
  version: "latest"
  container_name: "gitea"
  data_folder: "data" 
  directory: "/opt/gitea"
  inner_data_path: "/data"
  port_ssh: "22"
  port_http: "8080"
  db_type: "postgres"
  db_user: "gitea"
  db_name: "gitea"
  db_host: "{{ docker_internal_net }}.{{ postgres.net_addr }}:{{ postgres.internal_port }}"
  net_addr: "20"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.gitea.rule=Host(`gitea.alexandrshapkin.ru`)"
    - "traefik.http.routers.gitea.entrypoints=websecure"
    - "traefik.http.routers.gitea.tls.certresolver={{ traefik_resolver }}"
    - "traefik.http.services.gitea.loadbalancer.server.port=3000"